GET http://localhost:3001/api/persons/

###
POST https://floating-citadel-38949.herokuapp.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "s",
    "number": "46"
}

###
DELETE http://localhost:3001/api/persons/2